### ISSUE TITLE
mw.messages shows wrong metadata

### ISSUE THREAD

**Issue by siddharthvp** [galobtter/shortdesc-helper#3]
Running `mw.messages` in the devtools shows a `@metadata` field with `{author: Galobtter}`, which is misleading since this mw.messages has messages used by several tools, most notably MW core and extensions. 

<img width="798" alt="Screenshot 2021-03-12 at 11 06 17 AM" src="https://user-images.githubusercontent.com/31818903/110897276-2acb6980-8323-11eb-8927-b532a6577583.png">

**Comment by mmiyer** [comment]
Thanks for reporting, fixed in [this commit to libSettings](https://github.com/wikimedia-gadgets/libSettings/commit/3ba1727442927b4626683155e77b9fb18a609979).
