### ISSUE TITLE
merge Shortdesc-helper.css and Shortdesc-helper-pagestyles-vector.css?

### ISSUE THREAD

**Issue by NovemLinguae** [galobtter/shortdesc-helper#9]
All the styles in the file `Shortdesc-helper-pagestyles-vector.css` contain `.skin-vector`, so it should be safe to merge it with the file `Shortdesc-helper.css`. Both files are tiny, so it may not be worth the increased complexity of having the files separated, and having two different gadgets. Performance issues should be negligible.

* [ ] Cut and paste contents of Shortdesc-helper-pagestyles-vector.css into Shortdesc-helper.css. Save. Merge.
* [ ] Deploy
* [ ] Turn off and delete gadget Shortdesc-helper-pagestyles-vector by editing https://en.wikipedia.org/wiki/MediaWiki:Gadgets-definition
* [ ] Delete file Shortdesc-helper-pagestyles-vector.css. Merge.
* [ ] Deploy

<img width="958" alt="image" src="https://github.com/wikimedia-gadgets/shortdesc-helper/assets/79697282/c191a81d-1897-4aa2-849e-7f07ec6d6cd8">

**Comment by Galobtter** [comment]
Sorry no the point of this being separate is that a css only gadget is page blocking but a css in a JavaScript gadget is loaded later. Doing it this way avoids a FOUC where the short description jumps around.

**Comment by mmiyer** [comment]
Sorry no the point of this being separate is that a css only gadget is page blocking but a css in a JavaScript gadget is loaded later. Doing it this way avoids a FOUC where the short description jumps around.
